[metadata]
name = deap
version = 0.0.1
description = Dense Attentive Probing
url = https://github.com/timojl/deap
author = Timo Lueddecke
author_email = yourname@example.com

[options]
packages = find:
python_requires = >=3.10
include_package_data = True
package_dir =
    = .

[options.packages.find]
where = .
